apiVersion: v1
kind: ReplicationController
metadata:
  name: rancher-ingress-controller
  labels:
    k8s-app: rancher-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: rancher-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: rancher-ingress-lb
        name: rancher-ingress-lb
    spec:
      containers:
      - image: rancher/rancher-ingress:dev
        name: rancher-ingress-lb
        env:
          - name: CATTLE_URL
            value: "http://10.0.2.2:8080/v1"
          - name: CATTLE_ACCESS_KEY
            value: "41C575A65B3FFA8E56D7"
          - name: CATTLE_SECRET_KEY
            value: "38ewXco3uagrLn8QkfwCuS8KUVvkXR75Zh6J8QeV"
          - name: KUBERNETES_SERVER
            value: "http://master:80"
        args:
        - rancher-ingress
        - --lb-controller=kubernetes
        - --lb-provider=rancher