apiVersion: v1
kind: ReplicationController
metadata:
  name: rancher-ingress-controller
  labels:
    k8s-app: rancher-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: rancher-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: rancher-ingress-lb
        name: rancher-ingress-lb
    spec:
      containers:
      - image: rancher/rancher-ingress:dev
        name: rancher-ingress-lb
        env:
          - name: CATTLE_URL
            value: "http://10.0.2.2:8080/v1"
          - name: CATTLE_ACCESS_KEY
            value: "51313AE0910ABF660506"
          - name: CATTLE_SECRET_KEY
            value: "pLRL6tC4Vr1gY2zQ4QfmmkuPdmQvkHoADmDYcsD4"
          - name: KUBERNETES_SERVER
            value: "http://master:80"
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - rancher-ingress
        - --lb-controller=kubernetes
        - --lb-provider=rancher